MovieTime/Entities/WatchParty.cs
using System;
using System.Collections.Generic;

namespace MovieTime.Entities
{
    public partial class WatchParty
    {
        public WatchParty()
        {
            UserWatchPartyXref = new HashSet<UserWatchPartyXref>();
        }

        public int WatchPartyId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<UserWatchPartyXref> UserWatchPartyXref { get; set; }
    }
}

MovieTime/Models/WatchParty.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieTime.Models
{
    public class WatchParty
    {
        public int? WatchPartyId { get; set; }
        public string PartyName { get; set; }
        public IEnumerable<string> Users { get; set; }
    }
}

MovieTime/ViewModels/WatchParty/WatchPartyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieTime.ViewModels.WatchParty
{
    public class WatchPartyViewModel
    {
        public IEnumerable<string> Users { get; set; } = new List<string>();
        public IEnumerable<string> Movies { get; set; }
        public int? WatchPartyId { get; set; }
        public string Name { get; set; }
        public string UsersAsSingleString
        {
            get
            {
                return string.Join(", ", Users);
            }
            set
            {
                Users = value.Split(',').Select(x => x.Trim());
            }
        }
    }
}

MovieTime/Controllers/WatchPartyController.cs
using Microsoft.AspNetCore.Mvc;
using MovieTime.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.IO;
using CsvHelper;
using MovieTime.ViewModels.WatchParty;
using System.Collections.Generic;
using System.Linq;
using CsvHelper.Configuration;
using System;
using MovieTime.Services;

namespace MovieTime.Controllers
{
    [Authorize]
    public class WatchPartyController : Controller
    {
        private readonly WatchPartyService _watchPartyService;
        public WatchPartyController(WatchPartyService watchPartyService)
        {
            _watchPartyService = watchPartyService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var watchPartyModel = await _watchPartyService.GetWatchPartiesByUser(HttpContext.User.Identity.Name);
            var watchPartyViewModels = watchPartyModel.Select(x => new WatchPartyViewModel
            {
                WatchPartyId = x.WatchPartyId,
                Users = x.Users,
                Name = x.PartyName
            });

            return View(watchPartyViewModels);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? WatchPartyId)
        {
            if(WatchPartyId == null)
            {
                return View(new WatchPartyViewModel());
            }
            else
            {
                var model = await _watchPartyService.GetWatchPartyById(WatchPartyId.Value);
                var viewModel = new WatchPartyViewModel
                {
                    Name = model.PartyName,
                    Users = model.Users,
                    WatchPartyId = model.WatchPartyId
                };
                return View(viewModel);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WatchPartyViewModel watchParty)
        {
            var model = new WatchParty
            {
                Users = watchParty.Users,
                PartyName = watchParty.Name,
                WatchPartyId = watchParty.WatchPartyId
            };

            if(watchParty.WatchPartyId == null)
            {
               await  _watchPartyService.InsertWatchParty(model);
            }
            else
            {
               await _watchPartyService.UpdateWatchParty(model);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetMovieSuggestion(int WatchPartyId)
        {
            string movieSuggestion = await _watchPartyService.GetMovieRecomendation(WatchPartyId);
            return Ok(movieSuggestion);
        }
    }
}

MovieTime/Views/WatchParty/Edit.cshtml
@model MovieTime.ViewModels.WatchParty.WatchPartyViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="WatchPartyId" class="form-control" type="hidden"/>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsersAsSingleString" class="control-label"></label>
                <input asp-for="UsersAsSingleString" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MovieTime/Views/WatchParty/Index.cshtml
@model IEnumerable<MovieTime.ViewModels.WatchParty.WatchPartyViewModel>

@{
    ViewData["Title"] = "Watch Parties";
}
<h2 class="row">Watch Party!!</h2>

<div class="row">
    <h4>Watch Parties</h4>
    <hr />
    @foreach (var party in Model)
    {
        <h4>@party.Name</h4>
        <div class="col-md-4 watch-party">
            <ul>
                @foreach (var user in party.Users)
                {
                    <li>@user</li>
                }
            </ul>
            <a class="btn btn-primary" role="button" asp-controller="WatchParty" asp-action="Edit" asp-route-WatchPartyId="@party.WatchPartyId">Edit</a>
            <button class="btn btn-primary" onclick="GetSuggestion(@party.WatchPartyId)">Generate Suggestion</button>
        </div>
    }
</div>
<br />
<br />
<div>
    <a asp-controller="WatchParty" asp-action="Edit">Create New</a>
    <br />
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

<script>
    function GetSuggestion(watchPartyId) {
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetMovieSuggestion")',
            data: {
                WatchPartyId: watchPartyId
            },
            success: function (result) {
                alert(result);
            }
        });

    }
</script>