MovieTime/Controllers/OverwatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieTime.Entities.Overwatch;
using MovieTime.Models;
using MovieTime.Services.Overwatch;
using MovieTime.ViewModels.Overwatch;

namespace MovieTime.Controllers
{
    [Authorize]
    public class OverwatchController : Controller
    {
        private readonly OverwatchContext _overwatchDb;
        private readonly MatchService _matchService;
        public OverwatchController(OverwatchContext overWatchDb, MatchService matchService)
        {
            _overwatchDb = overWatchDb;
            _matchService = matchService;
        }

        public IActionResult Index()
        {
            var matchEntities = _overwatchDb.Match
                .Include(x => x.PlayerMatchXref)
                    .ThenInclude(x => x.Player)
                .Include(x => x.Map)
                .ToList();

            var matchHistory = new List<MatchHistoryViewModel>();
            foreach (var match in matchEntities)
            {
                matchHistory.Add(new MatchHistoryViewModel
                {
                    MapName = match.Map.Name,
                    IsVictory = match.Victory,
                    EndTime = match.Timestamp,
                    PlayerRole = match.PlayerMatchXref.ToDictionary(x => x.Player.Name, x => x.Role)
                });
            }

            return View(matchHistory);
        }

        [HttpGet]
        public IActionResult AddMatch()
        {
            var playerSelectList = _overwatchDb.Player
                .Select(x => new SelectListItem
                {
                    Value = x.PlayerId.ToString(),
                    Text = x.Name
                }).ToList();
            playerSelectList.Add(new SelectListItem { Text = "n/a", Value = "-1", Selected = true });
            var mapSelectList = _overwatchDb.Map
                .Select(x => new SelectListItem
                {
                    Value = x.MapId.ToString(),
                    Text = x.Name
                }).OrderBy(x => x.Text);

            var mmm = new CreateMatchViewModel
            {
                FirstDps = playerSelectList,
                SecondDps = playerSelectList,
                FirstHealer = playerSelectList,
                SecondHealer = playerSelectList,
                FirstTank = playerSelectList,
                SecondTank = playerSelectList,
                Map = mapSelectList
            };

            return View(mmm);
        }

        [HttpPost]
        public IActionResult AddMatch(CreateMatchViewModel match)
        {
            if (MatchContainsDuplicatePlayers(match))
            {
                return View("Error", new ErrorViewModel { Message = "Cannot contain duplicate players" });
            }

            var newMatch = new Match
            {
                MapId = int.Parse(match.MapId),
                Victory = match.IsVictory
            };
            _overwatchDb.Match.Add(newMatch);
            _overwatchDb.SaveChanges();

            if (match.FirstDpsId != "-1")
            {
                _overwatchDb.Add(new PlayerMatchXref
                {
                    PlayerId = int.Parse(match.FirstDpsId),
                    Role = "dps",
                    MatchId = newMatch.MatchId
                });
            }
            if (match.SecondDpsId != "-1")
            {
                _overwatchDb.Add(new PlayerMatchXref
                {
                    PlayerId = int.Parse(match.SecondDpsId),
                    Role = "dps",
                    MatchId = newMatch.MatchId
                });
            }
            if (match.FirstTankId != "-1")
            {
                _overwatchDb.Add(new PlayerMatchXref
                {
                    PlayerId = int.Parse(match.FirstTankId),
                    Role = "tank",
                    MatchId = newMatch.MatchId
                });
            }
            if (match.SecondTankId != "-1")
            {
                _overwatchDb.Add(new PlayerMatchXref
                {
                    PlayerId = int.Parse(match.SecondTankId),
                    Role = "tank",
                    MatchId = newMatch.MatchId
                });
            }
            if (match.FirstHealerId != "-1")
            {
                _overwatchDb.Add(new PlayerMatchXref
                {
                    PlayerId = int.Parse(match.FirstHealerId),
                    Role = "heal",
                    MatchId = newMatch.MatchId
                });
            }
            if (match.SecondHealerId != "-1")
            {
                _overwatchDb.Add(new PlayerMatchXref
                {
                    PlayerId = int.Parse(match.SecondHealerId),
                    Role = "heal",
                    MatchId = newMatch.MatchId
                });
            }

            _overwatchDb.SaveChanges();

            return RedirectToAction("Index");
        }

        private bool MatchContainsDuplicatePlayers(CreateMatchViewModel match)
        {
            var playerIds = new List<string>
            {
                match.FirstDpsId,
                match.SecondDpsId,
                match.FirstHealerId,
                match.SecondHealerId,
                match.FirstTankId,
                match.SecondTankId
            };

            var playerCounter = playerIds.Where(x => x != "-1").Count();

            return playerCounter != (playerIds.Distinct().Count() - 1);
        }

        [HttpGet]
        public IActionResult PlayerRoleStats(string playerIdentifier = null)
        {
            if (playerIdentifier != null)
            {
                return GetRoleStatsForPlayer(playerIdentifier);
            }
            var roleRecords = _matchService.GetPlayerRoleRecords();

            var viewModels = roleRecords.Select(x => new PlayerRoleStatsViewModel
            {
                PlayerId = x.PlayerId,
                PlayerName = x.PlayerName,
                Losses = x.Losses,
                Wins = x.Wins,
                Role = x.Role
            });

            ViewBag.PlayerSelectList = _overwatchDb.Player.Select(x => new SelectListItem
            {
                Value = x.PlayerId.ToString(),
                Text = x.Name
            }).ToList();

            ViewBag.PlayerSelectList.Add(new SelectListItem
            {
                Value = "All",
                Selected = true,
                Text = "All"
            });

            return View(viewModels);
        }

        private IActionResult GetRoleStatsForPlayer(string playerIdentifier)
        {
            var roleRecords = new List<Models.ApiModels.PlayerRoleRecord>();
            if (playerIdentifier == "All")
            {
                roleRecords = _matchService.GetPlayerRoleRecords().ToList();
            }
            else
            {
                roleRecords = _matchService.GetPlayerRoleRecords(playerIdentifier).ToList();
            }

            var viewModels = roleRecords.Select(x => new PlayerRoleStatsViewModel
            {
                PlayerId = x.PlayerId,
                PlayerName = x.PlayerName,
                Losses = x.Losses,
                Wins = x.Wins,
                Role = x.Role
            });

            return PartialView("_playerRoleStatsTable", viewModels);
        }
    }
}

MovieTime/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieTime</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/main.css" />
        <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MovieTime</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="WatchParty" asp-action="Index">Watch Parties</a></li>
                    <li><a asp-controller="Account" asp-action="LogoutAsync">Logout</a></li>
                    <li><a asp-controller="Overwatch" asp-action="Index">Overwatch Stats</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MovieTime</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/tinymce/tinymce.min.js"></script>
        <script src="~/lib/tinymce/jquery.tinymce.min.js"></script>
        <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/tinymce/tinymce.min.js"></script>
        <script src="~/lib/tinymce/jquery.tinymce.min.js"></script>
        <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>